version: "2.2"

services:
  sonarqube:
    image: sonarqube:7.1
    depends_on:
      - sonar-db
    container_name: 'sonarqube'
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonar-db:5432/sonar
    volumes:
      - /opt/sonarqube/conf
      - /opt/sonarqube/data
      - /opt/sonarqube/extensions

  sonar-db:
    image: postgres:12.2
    container_name: 'sonar-db'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - TZ=Japan
    volumes:
      - /var/lib/postgresql/data

